// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaConvocatorias.Infraestructura.Datos;

#nullable disable

namespace SASI.MigrationsSasi
{
    [DbContext(typeof(SasiDbContext))]
    [Migration("20260816170504_InicialSasi")]
    partial class InicialSasi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SASI.Dominio.Modelo.Correlativo", b =>
                {
                    b.Property<string>("Entidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("int");

                    b.HasKey("Entidad");

                    b.ToTable("Correlativo", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Objeto", b =>
                {
                    b.Property<int>("IdObjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObjeto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdPadre")
                        .HasColumnType("int");

                    b.Property<int>("IdSistema")
                        .HasColumnType("int");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdObjeto");

                    b.HasIndex("IdPadre");

                    b.HasIndex("IdSistema");

                    b.ToTable("Objeto", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Oficina", b =>
                {
                    b.Property<int>("IdOficina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOficina"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("IdOficinaPadre")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOficina");

                    b.ToTable("Oficina", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSistema")
                        .HasColumnType("int");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.HasIndex("IdSistema");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.RolObjeto", b =>
                {
                    b.Property<int>("IdRolObjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolObjeto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdObjeto")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRolObjeto");

                    b.HasIndex("IdObjeto");

                    b.HasIndex("IdRol");

                    b.ToTable("RolObjeto", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Sistema", b =>
                {
                    b.Property<int>("IdSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSistema"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSistema");

                    b.ToTable("Sistemas", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.UsuarioSistema", b =>
                {
                    b.Property<int>("IdUsuarioSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioSistema"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuarioSistema");

                    b.HasIndex("RolId");

                    b.HasIndex("SistemaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioSistema", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Objeto", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Objeto", "ObjetoPadre")
                        .WithMany("Hijos")
                        .HasForeignKey("IdPadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany()
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetoPadre");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Rol", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany("Roles")
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.RolObjeto", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Objeto", "Objeto")
                        .WithMany()
                        .HasForeignKey("IdObjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SASI.Dominio.Modelo.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objeto");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.UsuarioSistema", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany("Usuarios")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SASI.Dominio.Modelo.Usuario", null)
                        .WithMany("SistemasAsignados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Objeto", b =>
                {
                    b.Navigation("Hijos");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Sistema", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Usuario", b =>
                {
                    b.Navigation("SistemasAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
