// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaConvocatorias.Infraestructura.Datos;

#nullable disable

namespace SASI.MigrationsSasi
{
    [DbContext(typeof(SasiDbContext))]
    [Migration("20260819164232_AgregarOperacionSoporte")]
    partial class AgregarOperacionSoporte
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SASI.Dominio.Modelo.Correlativo", b =>
                {
                    b.Property<string>("Entidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("int");

                    b.HasKey("Entidad");

                    b.ToTable("Correlativo", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.EstadoOperativoSistema", b =>
                {
                    b.Property<int>("IdEstadoOperativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoOperativo"));

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioRegistro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstadoOperativo");

                    b.HasIndex("SistemaId");

                    b.ToTable("EstadoOperativoSistema", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Incidencia", b =>
                {
                    b.Property<int>("IdIncidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncidencia"));

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAtencion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioReporte")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIncidencia");

                    b.HasIndex("SistemaId");

                    b.ToTable("Incidencia", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Objeto", b =>
                {
                    b.Property<int>("IdObjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObjeto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdPadre")
                        .HasColumnType("int");

                    b.Property<int>("IdSistema")
                        .HasColumnType("int");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdObjeto");

                    b.HasIndex("IdPadre");

                    b.HasIndex("IdSistema");

                    b.ToTable("Objeto", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Oficina", b =>
                {
                    b.Property<int>("IdOficina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOficina"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("IdOficinaPadre")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOficina");

                    b.ToTable("Oficina", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSistema")
                        .HasColumnType("int");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.HasIndex("IdSistema");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.RolObjeto", b =>
                {
                    b.Property<int>("IdRolObjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRolObjeto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdObjeto")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRolObjeto");

                    b.HasIndex("IdObjeto");

                    b.HasIndex("IdRol");

                    b.ToTable("RolObjeto", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Sistema", b =>
                {
                    b.Property<int>("IdSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSistema"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AreaDuenaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoCicloVida")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOperativoActual")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaPuestaProduccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaPruebaRestauracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PoliticaRespaldo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableFuncional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableTecnico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RpoHoras")
                        .HasColumnType("int");

                    b.Property<int?>("RtoHoras")
                        .HasColumnType("int");

                    b.Property<string>("VersionActual")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSistema");

                    b.HasIndex("AreaDuenaId");

                    b.ToTable("Sistemas", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.SistemaContrato", b =>
                {
                    b.Property<int>("IdSistemaContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSistemaContrato"));

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CostoAnual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroContrato")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SLA_Detalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.HasKey("IdSistemaContrato");

                    b.HasIndex("SistemaId");

                    b.ToTable("SistemaContrato", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.SistemaDocumento", b =>
                {
                    b.Property<int>("IdSistemaDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSistemaDocumento"));

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("RutaArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioSubida")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSistemaDocumento");

                    b.HasIndex("SistemaId");

                    b.ToTable("SistemaDocumento", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.SistemaVersion", b =>
                {
                    b.Property<int>("IdSistemaVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSistemaVersion"));

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Changelog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entorno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaDespliegue")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioDespliegue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSistemaVersion");

                    b.HasIndex("SistemaId");

                    b.ToTable("SistemaVersion", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.SolicitudAcceso", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("AprobadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AuditFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AuditFechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUsuarioCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditUsuarioModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentarioRespuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpCreacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpModificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("RolId");

                    b.HasIndex("SistemaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitudAcceso", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.UsuarioSistema", b =>
                {
                    b.Property<int>("IdUsuarioSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioSistema"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("SistemaId")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdUsuarioSistema");

                    b.HasIndex("RolId");

                    b.HasIndex("SistemaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioSistema", (string)null);
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.EstadoOperativoSistema", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany("EstadosOperativos")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Incidencia", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany("Incidencias")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Objeto", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Objeto", "ObjetoPadre")
                        .WithMany("Hijos")
                        .HasForeignKey("IdPadre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany()
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetoPadre");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Rol", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany("Roles")
                        .HasForeignKey("IdSistema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.RolObjeto", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Objeto", "Objeto")
                        .WithMany()
                        .HasForeignKey("IdObjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SASI.Dominio.Modelo.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objeto");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Sistema", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Oficina", "AreaDuena")
                        .WithMany()
                        .HasForeignKey("AreaDuenaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AreaDuena");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.SistemaContrato", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany("Contratos")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.SistemaDocumento", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany("Documentos")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.SistemaVersion", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany("Versiones")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.SolicitudAcceso", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany()
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.UsuarioSistema", b =>
                {
                    b.HasOne("SASI.Dominio.Modelo.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SASI.Dominio.Modelo.Sistema", "Sistema")
                        .WithMany("Usuarios")
                        .HasForeignKey("SistemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SASI.Dominio.Modelo.Usuario", null)
                        .WithMany("SistemasAsignados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Objeto", b =>
                {
                    b.Navigation("Hijos");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Sistema", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Documentos");

                    b.Navigation("EstadosOperativos");

                    b.Navigation("Incidencias");

                    b.Navigation("Roles");

                    b.Navigation("Usuarios");

                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("SASI.Dominio.Modelo.Usuario", b =>
                {
                    b.Navigation("SistemasAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
